### ISSUE TITLE
adding new firmware without building the website

### ISSUE THREAD

**Issue by greg-norris** [ghi-electronics/due-console#45]
Is it possible to update file in the repo that in turn updates the list of available versions without rebuilding the website?

**Comment by dudedigital** [comment]
This is not possible. The `docs` directory is auto-generated on compile. While you could modify a file within the `docs` folder, any changes to the codebase that require a re-compile and push would override your changes. Thus, you'd have to modify the file in two places which kind of negates the ease. Downside of trying to host websites with github pages.

**Comment by gus-ghielec** [comment]
Why can't the live website points and use this folder directly? https://github.com/ghi-electronics/due-console/tree/master/public/firmware

**Comment by dudedigital** [comment]
The reason this wasn't possible is because we were building the site locally and uploading the output (`docs` folder) for Github pages. This meant if you only updated a file in the repo, it wasn't shown on the site, you'd have to re-build the site.

I was avoiding having to do this in case I couldn't figure it out, but luckily, I was able to configure building the site with Github Actions before deploying the page. Now you no longer need to build locally. This completely eliminates the `docs` folder. Now if you commit a change, it's all automated. It does take an additional 30-40 seconds due to the two step process, but that's okay.

You can now commit `firmware.json` or `demos.json` changes to update the site.
